server:
  port: 8081
  baseURL: "/"
  database: "/boot/config/plugins/filebrowser_quantum/database.db"
  logging:
    - levels: "info|debug|warning|error"
      output: "/var/log/filebrowser_quantum.log"
  sources:
    - path: "/"
      name: "Root Dir"
      config:
  filesystem:
    createFilePermission: "777"
    createDirectoryPermission: "777"
userDefaults:
  darkMode: true
  permissions:
    admin: true
    modify: true
    download: true
