server:
  port: 8081
  baseURL: "/"
  database: "/mnt/user/appdata/filebrowser_quantum/database.db"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/mnt"
      name: "mnt"
      config:
        denyByDefault: false
        defaultEnabled: true
userDefaults:
  darkMode: true
  permissions:
    admin: true
    modify: true
    download: true
